[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=1
startretries=3
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:redis]
command=/usr/bin/redis-server --daemonize no --loglevel warning
autostart=true
autorestart=true
priority=2
stdout_logfile=/dev/null
stderr_logfile=/dev/null
